### ISSUE TITLE
[Feat] 상담 채팅방 생성

### ISSUE THREAD

**Issue by moonyaeyoon** [UMC-Mini/UMC-Mini-Project-BackEnd#4]
## 📝 개요
- 이름과 전화번호를 받아 상담 채팅방을 생성한다.

## ✔️ To-Do
- [ ] 실시간 채팅 세팅
- [ ] 채팅 관련 entity 생성
- [ ] 채팅방 생성 API
## 👀 ETC
- 참고자료 등 기타 내용 작성
